version: "3.3"
services:
  backend:
    build:
      context: ./backend
    container_name: stopportal-backend
    ports:
      - "8000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/
      args:
        FRONTEND_ENV: dev
        API_BASE_URL: ${VUE_APP_API_URL}
    container_name: stopportal-frontend
    command: ["cp", "-r", "/app/dist/.", "/staticfiles/"]
    volumes:
      - static:/staticfiles

  gateway:
#    image: nginx:1.25
    build:
      context: ./infra/nginx
    container_name: gateway
    links:
      - backend
    ports:
      - "9000:80"
    volumes:
      - static:/usr/share/nginx/html/
#      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

volumes:
  static:

networks:
  app-network:
    driver: bridge