version: "3.3"
services:
  backend:
    image: dakmaev/stopportal-backend
    networks:
      - app-network

  frontend:
    image: dakmaev/stopportal-frontend
    command: [ "cp", "-r", "/app/dist/.", "/staticfiles/" ]
    volumes:
      - static:/staticfiles

  gateway:
    image: dakmaev/stopportal-gateway
    links:
      - backend
    ports:
      - "9000:80"
    volumes:
      - static:/usr/share/nginx/html/
    networks:
      - app-network

volumes:
  static:

networks:
  app-network:
    driver: bridge
