FROM python:3.11

WORKDIR /app/

COPY ./requirements.txt /app/
COPY ./app /app/backend/app

ENV PYTHONPATH=/app/

RUN pip install -r requirements.txt

CMD ["celery", "-A", " backend.app.worker.tasks", "worker", "--loglevel=info"]
