FROM python:3.11

WORKDIR /app/

RUN pip install poetry alembic pydantic-settings

COPY ./pyproject.toml /app/
COPY ./worker-start.sh /app/

COPY ./app /app/app
ENV PYTHONPATH=/app/

RUN poetry install

RUN chmod +x worker-start.sh

CMD ["bash", "worker-start.sh"]
# ENTRYPOINT bash
