version: "3.9"
services:
  backend:
    image: dakmaev/stopportal-backend:latest
    env_file:
      - .env
    links:
      - db
      - queue
    networks:
      - app-network

  worker:
    image: dakmaev/stopportal-celeryworker:latest
    env_file:
      - .env
    links:
      - db
      - queue
    deploy:
      mode: replicated
      replicas: 5
    networks:
      - app-network

  flower:
    image: mher/flower:2.0
    command: ["celery", "--broker=redis://queue:6379", "flower"]
    ports:
      - "5556:5555"
    links:
      - queue
      - db
    networks:
      - app-network

  migrator:
    image: dakmaev/stopportal-backend:latest
    env_file:
      - .env
    restart: on-failure
    command: alembic upgrade head
    links:
      - db
    networks:
      - app-network

  frontend:
    image: dakmaev/stopportal-frontend:latest
    env_file:
      - .env
    command: [ "cp", "-r", "/app/dist/.", "/staticfiles/" ]
    volumes:
      - static:/staticfiles

  gateway:
    image: dakmaev/stopportal-gateway:latest
    env_file:
      - .env
    links:
      - backend
    ports:
      - "${PORT}:80"
    volumes:
      - static:/usr/share/nginx/html/
    networks:
      - app-network

  db:
    image: postgres:16
    command: -c 'max_connections=300'
    env_file:
      - .env
    volumes:
      - dg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  queue:
    image: redis:7
    networks:
      - app-network

volumes:
  static:
  dg_data:
  backup:

networks:
  app-network:
    driver: bridge
