version: "3.9"
services:
  backend:
    build:
      context: ../backend
    container_name: stopportal-backend
    image: stopportal-backend:latest
    restart: always
    env_file: .env
    links:
      - db
      - queue
    networks:
      - app-network

  worker:
    build:
      context: ../backend
    container_name: stopportal-celeryworker
    image: stopportal-celeryworker:latest
    restart: always
    env_file: .env
    links:
      - db
      - queue
    networks:
      - app-network

  flower:
    image: mher/flower:2.0
    env_file:
      - .env
    command:
      - celery --broker=redis://queue:6379 flower --port=5555
    ports:
      - "5555:5555"
    links:
      - queue
      - db

  migrator:
    image: stopportal-backend:latest
    restart: no
    container_name: stopportal-migrator
    command: alembic upgrade head
    env_file: .env
    links:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      args:
        FRONTEND_ENV: dev
        API_BASE_URL: ${VUE_APP_API_URL}
    container_name: stopportal-frontend
    command: ["cp", "-r", "/app/dist/.", "/staticfiles/"]
    volumes:
      - static:/staticfiles

  gateway:
    build:
      context: ../infra/nginx
    container_name: stopportal-gateway
    links:
      - backend
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx/html/
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: stopportal-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - dg_data:/var/lib/postgresql/data
    networks:
      - app-network

  queue:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  static:
  dg_data:

networks:
  app-network:
    driver: bridge