"""empty message

Revision ID: defda519f59a
Revises: 78a1d46953fd
Create Date: 2023-10-10 23:04:36.130923

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "defda519f59a"
down_revision = "78a1d46953fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
