"""empty message

Revision ID: 521c09a43ac9
Revises: defda519f59a
Create Date: 2023-10-11 22:29:33.563913

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "521c09a43ac9"
down_revision = "defda519f59a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("name", sa.String(), nullable=True))
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_column("companies", "name")
    # ### end Alembic commands ###
