"""empty message

Revision ID: 7eb6cf35ed37
Revises: 91e4c60a4053
Create Date: 2023-09-25 21:32:39.428232

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7eb6cf35ed37"
down_revision = "91e4c60a4053"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cron_job_run", sa.Column("name", sa.String(), nullable=False))
    op.create_index(
        op.f("ix_cron_job_run_name"), "cron_job_run", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cron_job_run_name"), table_name="cron_job_run")
    op.drop_column("cron_job_run", "name")
    # ### end Alembic commands ###
