"""empty message

Revision ID: 78a1d46953fd
Revises: 0aa670f3eab2
Create Date: 2023-10-08 20:03:30.824444

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "78a1d46953fd"
down_revision = "0aa670f3eab2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tiker", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_tiker"), "companies", ["tiker"], unique=True)
    op.create_table(
        "companies_stop",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("ix_stock_tiker", table_name="stock")
    op.drop_table("stock")
    op.drop_table("stock_stop")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_stop",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("period", sa.VARCHAR(), nullable=False),
        sa.Column("value", sa.FLOAT(), nullable=False),
        sa.Column("stock_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stock.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stock",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("tiker", sa.VARCHAR(), nullable=False),
        sa.Column("type", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_stock_tiker", "stock", ["tiker"], unique=False)
    op.drop_table("companies_stop")
    op.drop_index(op.f("ix_companies_tiker"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
