"""empty message

Revision ID: 5e00b622e2b1
Revises: 0f8c216c1e64
Create Date: 2023-12-06 22:22:06.545824

"""
# revision identifiers, used by Alembic.
revision = "5e00b622e2b1"
down_revision = "0f8c216c1e64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
