"""empty message

Revision ID: 4548b2e865f0
Revises: 4b26048a9f97
Create Date: 2024-04-25 08:04:39.183189

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4548b2e865f0"
down_revision = "4b26048a9f97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "briefcase_shares",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.TIMESTAMP(), nullable=False),
        sa.Column(
            "last_updated",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("briefcase_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["briefcase_id"],
            ["briefcases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("briefcase_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("briefcase_shares")
    # ### end Alembic commands ###
