"""empty message

Revision ID: a1bf29f2daa2
Revises: 670e5b3d463d
Create Date: 2023-12-14 20:31:21.491225

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1bf29f2daa2"
down_revision = "670e5b3d463d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
