"""empty message

Revision ID: 670e5b3d463d
Revises: 5e00b622e2b1
Create Date: 2023-12-14 19:08:41.419515

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "670e5b3d463d"
down_revision = "5e00b622e2b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "briefcases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fill_up", sa.DECIMAL(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "briefcase_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("dividends", sa.DECIMAL(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("briefcase_items")
    op.drop_table("briefcases")
    # ### end Alembic commands ###
