"""empty message

Revision ID: 5ff103db9365
Revises: af2b6182a92b
Create Date: 2023-11-09 19:31:27.950746

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5ff103db9365"
down_revision = "af2b6182a92b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
