"""empty message

Revision ID: 1f5dd8cb5de7
Revises: c4f9d02faccd
Create Date: 2023-09-16 21:43:24.521004

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f5dd8cb5de7"
down_revision = "c4f9d02faccd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock", sa.Column("type", sa.String(), nullable=True))
    op.drop_column("stock", "is_moex")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock", sa.Column("is_moex", sa.BOOLEAN(), nullable=False))
    op.drop_column("stock", "type")
    # ### end Alembic commands ###
