"""empty message

Revision ID: e1ba5093f7bc
Revises: 7eb6cf35ed37
Create Date: 2023-10-02 23:10:54.100761

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1ba5093f7bc"
down_revision = "7eb6cf35ed37"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_tiker", table_name="stock")
    op.create_index(op.f("ix_stock_tiker"), "stock", ["tiker"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_tiker"), table_name="stock")
    op.create_index("ix_stock_tiker", "stock", ["tiker"], unique=False)
    # ### end Alembic commands ###
