"""empty message

Revision ID: 1d762e7a925c
Revises: c890745a5bcd
Create Date: 2024-01-10 19:49:37.893088

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1d762e7a925c"
down_revision = "c890745a5bcd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "briefcase_registry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_date",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.Enum("RUB", "USD", "EUR", name="currencyenum"),
            nullable=False,
        ),
        sa.Column(
            "operation",
            sa.Enum("BUY", "SELL", "DIVIDENDS", name="registryoperationenum"),
            nullable=False,
        ),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("amount", sa.DECIMAL(), nullable=True),
        sa.Column("price", sa.DECIMAL(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=True),
        sa.Column("briefcase_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["briefcase_id"],
            ["briefcases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("briefcase_registry")
    # ### end Alembic commands ###
