name: MR Stopportal workflow

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            ls -la
#    runs-on: ubuntu-latest
#    steps:
#  pytest:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Setup python
#      uses: actions/setup-python@v5
#      with:
#        python-version: 3.11
#
#    - name: Install poetry
#      uses: Gr1N/setup-poetry@v8
#
#    - name: Install dependencies
#      working-directory: backend
#      run: poetry install
#
#    - name: Run pytest check
#      working-directory: backend
#      run: poetry run pytest -vv .
#      env:
#        BACKEND_HOST: "0.0.0.0"
#  black:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup python
#        uses: actions/setup-python@v5
#        with:
#          python-version: 3.11
#
#      - name: Install poetry
#        uses: Gr1N/setup-poetry@v8
#
#      - name: Install dependencies
#        working-directory: backend
#        run: poetry install
#
#      - name: Run black check
#        working-directory: backend
#        run: poetry run black --check .
#  flake8:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup python
#        uses: actions/setup-python@v5
#        with:
#          python-version: 3.11
#
#      - name: Install poetry
#        uses: Gr1N/setup-poetry@v8
#
#      - name: Install dependencies
#        working-directory: backend
#        run: poetry install
#
#      - name: Run flake8 check
#        working-directory: backend
#        run: poetry run flake8 --count .
##  mypy:
##    runs-on: ubuntu-latest
##    steps:
##      - uses: actions/checkout@v4
##
##      - name: Setup python
##        uses: actions/setup-python@v5
##        with:
##          python-version: 3.11
##
##      - name: Install poetry
##        uses: Gr1N/setup-poetry@v8
##
##      - name: Install dependencies
##        working-directory: backend
##        run: poetry install
##
##      - name: Run mypy check
##        working-directory: backend
##        run: poetry run mypy .
#  frontend_lint:
#    name: Frontend tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up nodeJS
#        uses: actions/setup-node@v4
#        with:
#          node-version: 18
#
#      - name: Install dependencies
#        working-directory: frontend
#        run: npm install
#
#      - name: Install dependencies 2
#        working-directory: frontend
#        run: npm ci
#
#      - name: Lint
#        working-directory: frontend
#        run: npm run lint
#
#  send_message:
#    name: Sent notification to Telegram
#    runs-on: ubuntu-latest
#    needs:
#      - pytest
#      - black
#      - flake8
#      - frontend_lint
#    steps:
#      - name: Send message
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: Проверки PR успешно прошли!

